language: java
jdk:
  - openjdk11

branches:
  only:
    - master

#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

#gradlew 권한 부여
before_install:
  - chmod +x gradle

before_deploy:
  - zip -r springboot-bookstore *
  - mkdir -p deploy
  - mv springboot-bookstore.zip deploy/springboot-bookstore.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: donghoney-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로 설정
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: donghoney-springboot-build #버킷 이름
    key: springboot-bookstore.zip
    bundle_type: zip
    application: donghoney-springboot-bookstore #애플리케이션 이름
    deployment_group: donghoney-springboot-bookstore-group #애플리케이션 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - zone7907@gmail.com